"use client";

import Link from "next/link";
import { ArrowLeft, Scale, AlertTriangle, ShieldCheck, Terminal, FileText } from "lucide-react";
import { LandingFooter } from "@/components/landing/landing-footer";

export default function TermsOfService() {
  return (
    <main className="min-h-screen bg-zinc-950 text-zinc-100 font-sans selection:bg-omega-green/30">
      {/* Navigation */}
      <nav className="border-b border-zinc-900 bg-zinc-950/80 backdrop-blur-md sticky top-0 z-50">
        <div className="max-w-4xl mx-auto px-6 h-16 flex items-center justify-between">
          <Link
            href="/"
            className="flex items-center gap-2 text-zinc-400 hover:text-white transition-colors group"
          >
            <ArrowLeft className="w-4 h-4 group-hover:-translate-x-1 transition-transform" />
            <span className="font-medium">Return to OMEGA</span>
          </Link>
          <div className="flex items-center gap-2">
            <div className="w-2 h-2 rounded-full bg-omega-green animate-pulse" />
            <span className="text-xs font-mono text-omega-green">PROTOCOL_STATUS: LIVE</span>
          </div>
        </div>
      </nav>

      <div className="max-w-4xl mx-auto px-6 py-24">
        {/* Header */}
        <header className="mb-20">
          <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full border border-zinc-800 bg-zinc-900/50 mb-6">
            <Scale className="w-4 h-4 text-omega-green" />
            <span className="text-xs font-mono text-zinc-400">LEGAL_AGREEMENT_V1.0</span>
          </div>
          <h1 className="text-4xl md:text-6xl font-bold tracking-tighter mb-6">
            Terms of <br />
            <span className="text-transparent bg-clip-text bg-gradient-to-r from-omega-green to-emerald-500">
              Service & Liability
            </span>
          </h1>
          <p className="text-xl text-zinc-400 leading-relaxed max-w-2xl">
            By deploying OMEGA, you acknowledge that you are the sole architect of your financial infrastructure.
            We provide the blueprint; you build the vault.
          </p>
        </header>

        {/* Content */}
        <div className="space-y-16">

          {/* Not Financial Advice */}
          <section className="grid grid-cols-1 md:grid-cols-3 gap-8">
            <div className="md:col-span-2 space-y-4">
              <h2 className="text-2xl font-bold text-white flex items-center gap-3">
                <AlertTriangle className="w-6 h-6 text-amber-500" />
                Not Financial Advice
              </h2>
              <div className="prose prose-invert prose-zinc max-w-none">
                <p className="text-zinc-300 leading-relaxed">
                  OMEGA is a data aggregation and visualization tool. All reports, including "Flash Briefs," "Market Intelligence," and "Trajectory Projections," are generated by AI models based on public data and your inputs.
                </p>
                <p className="text-zinc-300 leading-relaxed">
                  <strong>These outputs are for informational purposes only.</strong> They do not constitute financial advice, investment recommendations, or trading signals. You are solely responsible for your investment decisions.
                </p>
              </div>
            </div>
            <div className="bg-zinc-900/50 border border-zinc-800 rounded-xl p-6 h-fit">
              <h3 className="text-emerald-400 font-mono text-xs mb-2 uppercase">Quick Summary</h3>
              <p className="text-zinc-400 text-sm">
                We are a software provider, not a financial advisor. Do your own research.
              </p>
            </div>
          </section>

          {/* No Fiduciary Relationship */}
          <section className="grid grid-cols-1 md:grid-cols-3 gap-8">
            <div className="md:col-span-2 space-y-4">
              <h2 className="text-2xl font-bold text-white flex items-center gap-3">
                <ShieldCheck className="w-6 h-6 text-zinc-500" />
                No Fiduciary Relationship
              </h2>
              <div className="prose prose-invert prose-zinc max-w-none">
                <p className="text-zinc-300 leading-relaxed">
                  Using OMEGA does not create a fiduciary relationship between you and the OMEGA development team. We are not custodians of your assets. We do not have access to your funds, private keys, or exchange accounts.
                </p>
              </div>
            </div>
            <div className="bg-zinc-900/50 border border-zinc-800 rounded-xl p-6 h-fit">
              <h3 className="text-emerald-400 font-mono text-xs mb-2 uppercase">Quick Summary</h3>
              <p className="text-zinc-400 text-sm">
                We don't hold your money. We don't manage your money. We just show you where it is.
              </p>
            </div>
          </section>

          {/* As-Is Software License */}
          <section className="grid grid-cols-1 md:grid-cols-3 gap-8">
            <div className="md:col-span-2 space-y-4">
              <h2 className="text-2xl font-bold text-white flex items-center gap-3">
                <Terminal className="w-6 h-6 text-zinc-500" />
                "As-Is" Software License
              </h2>
              <div className="prose prose-invert prose-zinc max-w-none">
                <p className="text-zinc-300 leading-relaxed">
                  The OMEGA suite (Core, Cloud, UI) is provided "as is," without warranty of any kind, express or implied. We do not guarantee:
                </p>
                <ul className="list-disc list-inside text-zinc-400 space-y-1">
                  <li>Continuous uptime of third-party APIs (Binance, Yahoo Finance).</li>
                  <li>Accuracy of AI-generated summaries (Groq/LLMs).</li>
                  <li>Bug-free operation of the open-source code.</li>
                </ul>
              </div>
            </div>
            <div className="bg-zinc-900/50 border border-zinc-800 rounded-xl p-6 h-fit">
              <h3 className="text-emerald-400 font-mono text-xs mb-2 uppercase">Quick Summary</h3>
              <p className="text-zinc-400 text-sm">
                It's open source. If it breaks or an API changes, you might need to fix it or wait for an update.
              </p>
            </div>
          </section>

          {/* User Responsibility */}
          <section className="grid grid-cols-1 md:grid-cols-3 gap-8">
            <div className="md:col-span-2 space-y-4">
              <h2 className="text-2xl font-bold text-white flex items-center gap-3">
                <FileText className="w-6 h-6 text-zinc-500" />
                User Responsibility
              </h2>
              <div className="prose prose-invert prose-zinc max-w-none">
                <p className="text-zinc-300 leading-relaxed">
                  You acknowledge that you are responsible for:
                </p>
                <ul className="list-disc list-inside text-zinc-400 space-y-1">
                  <li>Securing your hardware (Raspberry Pi, VPS) and network.</li>
                  <li>Managing your API keys and secrets (keeping them out of public repos).</li>
                  <li>Configuring your Supabase instance securely (RLS policies).</li>
                  <li>Compliance with local tax and financial regulations.</li>
                </ul>
              </div>
            </div>
            <div className="bg-zinc-900/50 border border-zinc-800 rounded-xl p-6 h-fit">
              <h3 className="text-emerald-400 font-mono text-xs mb-2 uppercase">Quick Summary</h3>
              <p className="text-zinc-400 text-sm">
                You are the admin. Security and compliance are on you.
              </p>
            </div>
          </section>

          {/* Target Objective Disclaimer */}
          <section className="bg-zinc-900 border border-zinc-800 rounded-xl p-8">
            <h2 className="text-xl font-bold text-white mb-4 font-mono">
              DISCLAIMER: THE "1M€ BY 2035" OBJECTIVE
            </h2>
            <p className="text-zinc-400 text-sm leading-relaxed mb-4">
              The "Trajectory Planner" and the "1M€ by 2035" goal are mathematical simulations based on compound interest formulas and your input variables (monthly contribution, expected yield).
            </p>
            <p className="text-zinc-400 text-sm leading-relaxed">
              <strong>Past performance is not indicative of future results.</strong> Achieving this target depends on market conditions, your discipline, and factors outside the scope of this software. OMEGA does not guarantee you will become a millionaire.
            </p>
          </section>

        </div>
      </div>

      <LandingFooter />
    </main>
  );
}
